// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: grpc/replication.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientBidStatus int32

const (
	ClientBidStatus_SUCCESS              ClientBidStatus = 0
	ClientBidStatus_FAIL_AUCTION_IS_DONE ClientBidStatus = 1
	ClientBidStatus_FAIL_BID_TOO_LOW     ClientBidStatus = 2
	ClientBidStatus_EXCEPTION            ClientBidStatus = 3
)

// Enum value maps for ClientBidStatus.
var (
	ClientBidStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL_AUCTION_IS_DONE",
		2: "FAIL_BID_TOO_LOW",
		3: "EXCEPTION",
	}
	ClientBidStatus_value = map[string]int32{
		"SUCCESS":              0,
		"FAIL_AUCTION_IS_DONE": 1,
		"FAIL_BID_TOO_LOW":     2,
		"EXCEPTION":            3,
	}
)

func (x ClientBidStatus) Enum() *ClientBidStatus {
	p := new(ClientBidStatus)
	*p = x
	return p
}

func (x ClientBidStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientBidStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_replication_proto_enumTypes[0].Descriptor()
}

func (ClientBidStatus) Type() protoreflect.EnumType {
	return &file_grpc_replication_proto_enumTypes[0]
}

func (x ClientBidStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientBidStatus.Descriptor instead.
func (ClientBidStatus) EnumDescriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{0}
}

type Nothing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nothing) Reset() {
	*x = Nothing{}
	mi := &file_grpc_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nothing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nothing) ProtoMessage() {}

func (x *Nothing) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nothing.ProtoReflect.Descriptor instead.
func (*Nothing) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{0}
}

type NodeInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip:port
	// i.e: 127.0.0.1:4356
	ConnectionAddr string `protobuf:"bytes,1,opt,name=connectionAddr,proto3" json:"connectionAddr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_grpc_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetConnectionAddr() string {
	if x != nil {
		return x.ConnectionAddr
	}
	return ""
}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bid           *ClientBid             `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=isFinal,proto3" json:"isFinal,omitempty"`
	IsValid       bool                   `protobuf:"varint,3,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_grpc_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{2}
}

func (x *Outcome) GetBid() *ClientBid {
	if x != nil {
		return x.Bid
	}
	return nil
}

func (x *Outcome) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Outcome) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type ClientBid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Amount        uint32                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Item          string                 `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientBid) Reset() {
	*x = ClientBid{}
	mi := &file_grpc_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBid) ProtoMessage() {}

func (x *ClientBid) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBid.ProtoReflect.Descriptor instead.
func (*ClientBid) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{3}
}

func (x *ClientBid) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientBid) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ClientBid) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type ClientBidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ClientBidStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=grpc.ClientBidStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientBidResp) Reset() {
	*x = ClientBidResp{}
	mi := &file_grpc_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientBidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBidResp) ProtoMessage() {}

func (x *ClientBidResp) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBidResp.ProtoReflect.Descriptor instead.
func (*ClientBidResp) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{4}
}

func (x *ClientBidResp) GetStatus() ClientBidStatus {
	if x != nil {
		return x.Status
	}
	return ClientBidStatus_SUCCESS
}

type Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Time) Reset() {
	*x = Time{}
	mi := &file_grpc_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{5}
}

func (x *Time) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IsLeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLeader      bool                   `protobuf:"varint,1,opt,name=isLeader,proto3" json:"isLeader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsLeader) Reset() {
	*x = IsLeader{}
	mi := &file_grpc_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsLeader) ProtoMessage() {}

func (x *IsLeader) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsLeader.ProtoReflect.Descriptor instead.
func (*IsLeader) Descriptor() ([]byte, []int) {
	return file_grpc_replication_proto_rawDescGZIP(), []int{6}
}

func (x *IsLeader) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

var File_grpc_replication_proto protoreflect.FileDescriptor

const file_grpc_replication_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/replication.proto\x12\x04grpc\"\t\n" +
	"\aNothing\"2\n" +
	"\bNodeInfo\x12&\n" +
	"\x0econnectionAddr\x18\x01 \x01(\tR\x0econnectionAddr\"`\n" +
	"\aOutcome\x12!\n" +
	"\x03bid\x18\x01 \x01(\v2\x0f.grpc.ClientBidR\x03bid\x12\x18\n" +
	"\aisFinal\x18\x02 \x01(\bR\aisFinal\x12\x18\n" +
	"\aisValid\x18\x03 \x01(\bR\aisValid\"S\n" +
	"\tClientBid\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12\x12\n" +
	"\x04item\x18\x03 \x01(\tR\x04item\">\n" +
	"\rClientBidResp\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.grpc.ClientBidStatusR\x06status\"$\n" +
	"\x04Time\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"&\n" +
	"\bIsLeader\x12\x1a\n" +
	"\bisLeader\x18\x01 \x01(\bR\bisLeader*]\n" +
	"\x0fClientBidStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x18\n" +
	"\x14FAIL_AUCTION_IS_DONE\x10\x01\x12\x14\n" +
	"\x10FAIL_BID_TOO_LOW\x10\x02\x12\r\n" +
	"\tEXCEPTION\x10\x032\xe5\x01\n" +
	"\x0eAuctionService\x12+\n" +
	"\x03Bid\x12\x0f.grpc.ClientBid\x1a\x13.grpc.ClientBidResp\x12&\n" +
	"\x06Result\x12\r.grpc.Nothing\x1a\r.grpc.Outcome\x12%\n" +
	"\x04Ping\x12\r.grpc.Nothing\x1a\x0e.grpc.IsLeader\x12+\n" +
	"\tReplicate\x12\x0f.grpc.ClientBid\x1a\r.grpc.Nothing\x12*\n" +
	"\rReplicateTime\x12\n" +
	".grpc.Time\x1a\r.grpc.NothingB\x15Z\x13replication-go/grpcb\x06proto3"

var (
	file_grpc_replication_proto_rawDescOnce sync.Once
	file_grpc_replication_proto_rawDescData []byte
)

func file_grpc_replication_proto_rawDescGZIP() []byte {
	file_grpc_replication_proto_rawDescOnce.Do(func() {
		file_grpc_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_replication_proto_rawDesc), len(file_grpc_replication_proto_rawDesc)))
	})
	return file_grpc_replication_proto_rawDescData
}

var file_grpc_replication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpc_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpc_replication_proto_goTypes = []any{
	(ClientBidStatus)(0),  // 0: grpc.ClientBidStatus
	(*Nothing)(nil),       // 1: grpc.Nothing
	(*NodeInfo)(nil),      // 2: grpc.NodeInfo
	(*Outcome)(nil),       // 3: grpc.Outcome
	(*ClientBid)(nil),     // 4: grpc.ClientBid
	(*ClientBidResp)(nil), // 5: grpc.ClientBidResp
	(*Time)(nil),          // 6: grpc.Time
	(*IsLeader)(nil),      // 7: grpc.IsLeader
}
var file_grpc_replication_proto_depIdxs = []int32{
	4, // 0: grpc.Outcome.bid:type_name -> grpc.ClientBid
	0, // 1: grpc.ClientBidResp.status:type_name -> grpc.ClientBidStatus
	4, // 2: grpc.AuctionService.Bid:input_type -> grpc.ClientBid
	1, // 3: grpc.AuctionService.Result:input_type -> grpc.Nothing
	1, // 4: grpc.AuctionService.Ping:input_type -> grpc.Nothing
	4, // 5: grpc.AuctionService.Replicate:input_type -> grpc.ClientBid
	6, // 6: grpc.AuctionService.ReplicateTime:input_type -> grpc.Time
	5, // 7: grpc.AuctionService.Bid:output_type -> grpc.ClientBidResp
	3, // 8: grpc.AuctionService.Result:output_type -> grpc.Outcome
	7, // 9: grpc.AuctionService.Ping:output_type -> grpc.IsLeader
	1, // 10: grpc.AuctionService.Replicate:output_type -> grpc.Nothing
	1, // 11: grpc.AuctionService.ReplicateTime:output_type -> grpc.Nothing
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_replication_proto_init() }
func file_grpc_replication_proto_init() {
	if File_grpc_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_replication_proto_rawDesc), len(file_grpc_replication_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_replication_proto_goTypes,
		DependencyIndexes: file_grpc_replication_proto_depIdxs,
		EnumInfos:         file_grpc_replication_proto_enumTypes,
		MessageInfos:      file_grpc_replication_proto_msgTypes,
	}.Build()
	File_grpc_replication_proto = out.File
	file_grpc_replication_proto_goTypes = nil
	file_grpc_replication_proto_depIdxs = nil
}
