// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: grpc/replication.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuctionService_HoldElection_FullMethodName   = "/grpc.AuctionService/HoldElection"
	AuctionService_EnterElection_FullMethodName  = "/grpc.AuctionService/EnterElection"
	AuctionService_ElectionWinner_FullMethodName = "/grpc.AuctionService/ElectionWinner"
	AuctionService_Replicate_FullMethodName      = "/grpc.AuctionService/Replicate"
)

// AuctionServiceClient is the client API for AuctionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuctionServiceClient interface {
	// BULLY ELECTION ALGORITHM RPC CALLS
	// Node sends this to start an election
	HoldElection(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Acknowledgement, error)
	// Node sends this to indicate that it's still alive + enter the election
	EnterElection(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Acknowledgement, error)
	// The winner of the election sends this to indicate that they won
	ElectionWinner(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Acknowledgement, error)
	// REPLICATION RPC CALLS
	Replicate(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type auctionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuctionServiceClient(cc grpc.ClientConnInterface) AuctionServiceClient {
	return &auctionServiceClient{cc}
}

func (c *auctionServiceClient) HoldElection(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, AuctionService_HoldElection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) EnterElection(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, AuctionService_EnterElection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) ElectionWinner(ctx context.Context, in *NodeInfo, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, AuctionService_ElectionWinner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auctionServiceClient) Replicate(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, AuctionService_Replicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuctionServiceServer is the server API for AuctionService service.
// All implementations must embed UnimplementedAuctionServiceServer
// for forward compatibility.
type AuctionServiceServer interface {
	// BULLY ELECTION ALGORITHM RPC CALLS
	// Node sends this to start an election
	HoldElection(context.Context, *NodeInfo) (*Acknowledgement, error)
	// Node sends this to indicate that it's still alive + enter the election
	EnterElection(context.Context, *NodeInfo) (*Acknowledgement, error)
	// The winner of the election sends this to indicate that they won
	ElectionWinner(context.Context, *NodeInfo) (*Acknowledgement, error)
	// REPLICATION RPC CALLS
	Replicate(context.Context, *Data) (*Acknowledgement, error)
	mustEmbedUnimplementedAuctionServiceServer()
}

// UnimplementedAuctionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuctionServiceServer struct{}

func (UnimplementedAuctionServiceServer) HoldElection(context.Context, *NodeInfo) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HoldElection not implemented")
}
func (UnimplementedAuctionServiceServer) EnterElection(context.Context, *NodeInfo) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterElection not implemented")
}
func (UnimplementedAuctionServiceServer) ElectionWinner(context.Context, *NodeInfo) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ElectionWinner not implemented")
}
func (UnimplementedAuctionServiceServer) Replicate(context.Context, *Data) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedAuctionServiceServer) mustEmbedUnimplementedAuctionServiceServer() {}
func (UnimplementedAuctionServiceServer) testEmbeddedByValue()                        {}

// UnsafeAuctionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuctionServiceServer will
// result in compilation errors.
type UnsafeAuctionServiceServer interface {
	mustEmbedUnimplementedAuctionServiceServer()
}

func RegisterAuctionServiceServer(s grpc.ServiceRegistrar, srv AuctionServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuctionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuctionService_ServiceDesc, srv)
}

func _AuctionService_HoldElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).HoldElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_HoldElection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).HoldElection(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_EnterElection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).EnterElection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_EnterElection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).EnterElection(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_ElectionWinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).ElectionWinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_ElectionWinner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).ElectionWinner(ctx, req.(*NodeInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuctionService_Replicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuctionServiceServer).Replicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuctionService_Replicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuctionServiceServer).Replicate(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// AuctionService_ServiceDesc is the grpc.ServiceDesc for AuctionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuctionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.AuctionService",
	HandlerType: (*AuctionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HoldElection",
			Handler:    _AuctionService_HoldElection_Handler,
		},
		{
			MethodName: "EnterElection",
			Handler:    _AuctionService_EnterElection_Handler,
		},
		{
			MethodName: "ElectionWinner",
			Handler:    _AuctionService_ElectionWinner_Handler,
		},
		{
			MethodName: "Replicate",
			Handler:    _AuctionService_Replicate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/replication.proto",
}
