// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/auction_system.proto

package auction_system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int64                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_auction_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

type RegisterBidderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderId      string                 `protobuf:"bytes,1,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBidderReq) Reset() {
	*x = RegisterBidderReq{}
	mi := &file_proto_auction_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBidderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBidderReq) ProtoMessage() {}

func (x *RegisterBidderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBidderReq.ProtoReflect.Descriptor instead.
func (*RegisterBidderReq) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterBidderReq) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

type RegisterBidderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBidderResp) Reset() {
	*x = RegisterBidderResp{}
	mi := &file_proto_auction_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBidderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBidderResp) ProtoMessage() {}

func (x *RegisterBidderResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBidderResp.ProtoReflect.Descriptor instead.
func (*RegisterBidderResp) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBidderResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterBidderResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlaceBidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderId      string                 `protobuf:"bytes,1,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidReq) Reset() {
	*x = PlaceBidReq{}
	mi := &file_proto_auction_system_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidReq) ProtoMessage() {}

func (x *PlaceBidReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidReq.ProtoReflect.Descriptor instead.
func (*PlaceBidReq) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceBidReq) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *PlaceBidReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlaceBidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResp) Reset() {
	*x = PlaceBidResp{}
	mi := &file_proto_auction_system_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResp) ProtoMessage() {}

func (x *PlaceBidResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResp.ProtoReflect.Descriptor instead.
func (*PlaceBidResp) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceBidResp) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PlaceBidResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetStatusResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Closed            bool                   `protobuf:"varint,1,opt,name=closed,proto3" json:"closed,omitempty"`
	HighestBid        int64                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	HighestBidder     string                 `protobuf:"bytes,3,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	RegisteredBidders []string               `protobuf:"bytes,4,rep,name=registered_bidders,json=registeredBidders,proto3" json:"registered_bidders,omitempty"`
	Deadline          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatusResp) Reset() {
	*x = GetStatusResp{}
	mi := &file_proto_auction_system_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResp) ProtoMessage() {}

func (x *GetStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResp.ProtoReflect.Descriptor instead.
func (*GetStatusResp) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatusResp) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *GetStatusResp) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *GetStatusResp) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *GetStatusResp) GetRegisteredBidders() []string {
	if x != nil {
		return x.RegisteredBidders
	}
	return nil
}

func (x *GetStatusResp) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type AuctionState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuctionId         int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	HighestBid        int64                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	HighestBidder     string                 `protobuf:"bytes,3,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	Closed            bool                   `protobuf:"varint,4,opt,name=closed,proto3" json:"closed,omitempty"`
	DeadlineUnix      int64                  `protobuf:"varint,5,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"`
	RegisteredBidders []string               `protobuf:"bytes,6,rep,name=registered_bidders,json=registeredBidders,proto3" json:"registered_bidders,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuctionState) Reset() {
	*x = AuctionState{}
	mi := &file_proto_auction_system_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionState) ProtoMessage() {}

func (x *AuctionState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionState.ProtoReflect.Descriptor instead.
func (*AuctionState) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{6}
}

func (x *AuctionState) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *AuctionState) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *AuctionState) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *AuctionState) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *AuctionState) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *AuctionState) GetRegisteredBidders() []string {
	if x != nil {
		return x.RegisteredBidders
	}
	return nil
}

type ElectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CandidateId   int64                  `protobuf:"varint,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionRequest) Reset() {
	*x = ElectionRequest{}
	mi := &file_proto_auction_system_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionRequest) ProtoMessage() {}

func (x *ElectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionRequest.ProtoReflect.Descriptor instead.
func (*ElectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{7}
}

func (x *ElectionRequest) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

type ElectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ResponderId   int64                  `protobuf:"varint,2,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElectionResponse) Reset() {
	*x = ElectionResponse{}
	mi := &file_proto_auction_system_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionResponse) ProtoMessage() {}

func (x *ElectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionResponse.ProtoReflect.Descriptor instead.
func (*ElectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{8}
}

func (x *ElectionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ElectionResponse) GetResponderId() int64 {
	if x != nil {
		return x.ResponderId
	}
	return 0
}

type LeaderAnnouncement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      int64                  `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderAnnouncement) Reset() {
	*x = LeaderAnnouncement{}
	mi := &file_proto_auction_system_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderAnnouncement) ProtoMessage() {}

func (x *LeaderAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_system_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderAnnouncement.ProtoReflect.Descriptor instead.
func (*LeaderAnnouncement) Descriptor() ([]byte, []int) {
	return file_proto_auction_system_proto_rawDescGZIP(), []int{9}
}

func (x *LeaderAnnouncement) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

var File_proto_auction_system_proto protoreflect.FileDescriptor

const file_proto_auction_system_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/auction_system.proto\x12\x0eauction_system\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x03R\x06fromId\"0\n" +
	"\x11RegisterBidderReq\x12\x1b\n" +
	"\tbidder_id\x18\x01 \x01(\tR\bbidderId\">\n" +
	"\x12RegisterBidderResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\vPlaceBidReq\x12\x1b\n" +
	"\tbidder_id\x18\x01 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"B\n" +
	"\fPlaceBidResp\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd6\x01\n" +
	"\rGetStatusResp\x12\x16\n" +
	"\x06closed\x18\x01 \x01(\bR\x06closed\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x03R\n" +
	"highestBid\x12%\n" +
	"\x0ehighest_bidder\x18\x03 \x01(\tR\rhighestBidder\x12-\n" +
	"\x12registered_bidders\x18\x04 \x03(\tR\x11registeredBidders\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xe1\x01\n" +
	"\fAuctionState\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x03R\n" +
	"highestBid\x12%\n" +
	"\x0ehighest_bidder\x18\x03 \x01(\tR\rhighestBidder\x12\x16\n" +
	"\x06closed\x18\x04 \x01(\bR\x06closed\x12#\n" +
	"\rdeadline_unix\x18\x05 \x01(\x03R\fdeadlineUnix\x12-\n" +
	"\x12registered_bidders\x18\x06 \x03(\tR\x11registeredBidders\"4\n" +
	"\x0fElectionRequest\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\x03R\vcandidateId\"Q\n" +
	"\x10ElectionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12!\n" +
	"\fresponder_id\x18\x02 \x01(\x03R\vresponderId\"1\n" +
	"\x12LeaderAnnouncement\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x03R\bleaderId2\xf4\x01\n" +
	"\x0eAuctionService\x12W\n" +
	"\x0eRegisterBidder\x12!.auction_system.RegisterBidderReq\x1a\".auction_system.RegisterBidderResp\x12E\n" +
	"\bPlaceBid\x12\x1b.auction_system.PlaceBidReq\x1a\x1c.auction_system.PlaceBidResp\x12B\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1d.auction_system.GetStatusResp2\xb4\x02\n" +
	"\vNodeService\x12M\n" +
	"\bElection\x12\x1f.auction_system.ElectionRequest\x1a .auction_system.ElectionResponse\x12L\n" +
	"\x0eAnnounceLeader\x12\".auction_system.LeaderAnnouncement\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\tHeartbeat\x12\x1b.auction_system.PingRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0eReplicateState\x12\x1c.auction_system.AuctionState\x1a\x16.google.protobuf.EmptyB%Z#auction_system/proto;auction_systemb\x06proto3"

var (
	file_proto_auction_system_proto_rawDescOnce sync.Once
	file_proto_auction_system_proto_rawDescData []byte
)

func file_proto_auction_system_proto_rawDescGZIP() []byte {
	file_proto_auction_system_proto_rawDescOnce.Do(func() {
		file_proto_auction_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_system_proto_rawDesc), len(file_proto_auction_system_proto_rawDesc)))
	})
	return file_proto_auction_system_proto_rawDescData
}

var file_proto_auction_system_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_auction_system_proto_goTypes = []any{
	(*PingRequest)(nil),           // 0: auction_system.PingRequest
	(*RegisterBidderReq)(nil),     // 1: auction_system.RegisterBidderReq
	(*RegisterBidderResp)(nil),    // 2: auction_system.RegisterBidderResp
	(*PlaceBidReq)(nil),           // 3: auction_system.PlaceBidReq
	(*PlaceBidResp)(nil),          // 4: auction_system.PlaceBidResp
	(*GetStatusResp)(nil),         // 5: auction_system.GetStatusResp
	(*AuctionState)(nil),          // 6: auction_system.AuctionState
	(*ElectionRequest)(nil),       // 7: auction_system.ElectionRequest
	(*ElectionResponse)(nil),      // 8: auction_system.ElectionResponse
	(*LeaderAnnouncement)(nil),    // 9: auction_system.LeaderAnnouncement
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_proto_auction_system_proto_depIdxs = []int32{
	10, // 0: auction_system.GetStatusResp.deadline:type_name -> google.protobuf.Timestamp
	1,  // 1: auction_system.AuctionService.RegisterBidder:input_type -> auction_system.RegisterBidderReq
	3,  // 2: auction_system.AuctionService.PlaceBid:input_type -> auction_system.PlaceBidReq
	11, // 3: auction_system.AuctionService.GetStatus:input_type -> google.protobuf.Empty
	7,  // 4: auction_system.NodeService.Election:input_type -> auction_system.ElectionRequest
	9,  // 5: auction_system.NodeService.AnnounceLeader:input_type -> auction_system.LeaderAnnouncement
	0,  // 6: auction_system.NodeService.Heartbeat:input_type -> auction_system.PingRequest
	6,  // 7: auction_system.NodeService.ReplicateState:input_type -> auction_system.AuctionState
	2,  // 8: auction_system.AuctionService.RegisterBidder:output_type -> auction_system.RegisterBidderResp
	4,  // 9: auction_system.AuctionService.PlaceBid:output_type -> auction_system.PlaceBidResp
	5,  // 10: auction_system.AuctionService.GetStatus:output_type -> auction_system.GetStatusResp
	8,  // 11: auction_system.NodeService.Election:output_type -> auction_system.ElectionResponse
	11, // 12: auction_system.NodeService.AnnounceLeader:output_type -> google.protobuf.Empty
	11, // 13: auction_system.NodeService.Heartbeat:output_type -> google.protobuf.Empty
	11, // 14: auction_system.NodeService.ReplicateState:output_type -> google.protobuf.Empty
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_auction_system_proto_init() }
func file_proto_auction_system_proto_init() {
	if File_proto_auction_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_system_proto_rawDesc), len(file_proto_auction_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_auction_system_proto_goTypes,
		DependencyIndexes: file_proto_auction_system_proto_depIdxs,
		MessageInfos:      file_proto_auction_system_proto_msgTypes,
	}.Build()
	File_proto_auction_system_proto = out.File
	file_proto_auction_system_proto_goTypes = nil
	file_proto_auction_system_proto_depIdxs = nil
}
